# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MedicalExaminationSchedule' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'MagicalRecord'
  # Pods for MedicalExaminationSchedule

  target 'MedicalExaminationScheduleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MedicalExaminationScheduleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
